<?php

namespace App\Http\Controllers\Widgets;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Backpack\CRUD\app\Http\Controllers\CrudController;
use Illuminate\Support\Facades\File;
use Illuminate\Support\Facades\Config;

class ArticleWidget extends CrudController
{
    private $extraData;

    public function setup() {
        $this->crud->setModel('App\Models\PageSectionWidget');
        $this->crud->setRoute(config('backpack.base.frontend_route_prefix') . '/pagesectionwidget');
        $this->crud->setEntityNameStrings('pagesectionwidget', 'pagesectionwidgets');

        $this->crud->addFields([
                [    // TEXT
                    'name' => 'title',
                    'label' => 'Title',
                    'type' => 'text',
                    'placeholder' => 'Your title here',
                ], [
                    'name' => 'slug',
                    'label' => 'Slug (URL)',
                    'type' => 'text',
                    'hint' => 'Will be automatically generated from your title, if left empty.',
                    // 'disabled' => 'disabled'
                ], [    // TEXT
                    'name' => 'date',
                    'label' => 'Date',
                    'type' => 'date',
                    'value' => date('Y-m-d'),
                ], [    // WYSIWYG
                    'name' => 'content',
                    'label' => 'Content',
                    'type' => 'ckeditor',
                    'placeholder' => 'Your textarea text here',
                ], [    // Image
                    'name' => 'image',
                    'label' => 'Image',
                    'type' => 'browse',
                ], [    // SELECT
                    'label' => 'Category',
                    'type' => 'select2',
                    'name' => 'category_id',
                    'entity' => 'category',
                    'attribute' => 'name',
                    'model' => "Backpack\NewsCRUD\app\Models\Category",
                ], [       // Select2Multiple = n-n relationship (with pivot table)
                    'label' => 'Tags',
                    'type' => 'select2_multiple',
                    'name' => 'tags', // the method that defines the relationship in your Model
                    'entity' => 'tags', // the method that defines the relationship in your Model
                    'attribute' => 'name', // foreign key attribute that is shown to user
                    'model' => "Backpack\NewsCRUD\app\Models\Tag", // foreign key model
                    'pivot' => true, // on create&update, do you need to add/delete pivot table entries?
                ], [    // ENUM
                    'name' => 'status',
                    'label' => 'Status',
                    'type' => 'enum',
                ], [    // CHECKBOX
                    'name' => 'featured',
                    'label' => 'Featured item',
                    'type' => 'checkbox',
                ],
            ], 'update/create/both');
    }

    public function create()
    {
        //$this->crud->hasAccessOrFail('create');
        //dd($this->crud);

        // prepare the fields you need to show
        $this->data = $this->extraData;

        $this->data['crud'] = $this->crud;
        $this->data['saveAction'] = $this->getSaveAction();
        $this->data['fields'] = $this->crud->getCreateFields();
        $this->data['title'] = "Edit widget";

        // load the view from /resources/views/vendor/backpack/crud/ if it exists, otherwise load the one in the package
        return view($this->crud->getCreateView(), $this->data);
    }

    public function edit($id)
    {
        return parent::edit($id); // TODO: Change the autogenerated stub
    }

    public function display($view)
    {
        return view('widget_types.' . $view, $this->data)->render();
    }

    public function setExtraData($data) {
        $this->extraData = $data;
    }

    public function setData($data) {
        $this->data['data'] = json_decode($data);
    }

    public function createSettings($requestData) {
        $background = str_replace("\\", "/", $requestData->input('widget_background'));
        return json_encode([
            'title' => $requestData->input('widget_title'),
            'subtitle' => $requestData->input('widget_subtitle'),
            'image' => $background
        ]);
    }
}
