<?php

namespace App\Http\Controllers\Widgets;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Backpack\CRUD\app\Http\Controllers\CrudController;

class BannerWidget extends CrudController
{
    private $extraData;

    public function setup() {
        $this->crud->setModel('App\Models\PageSectionWidget');
        $this->crud->setRoute(config('backpack.base.frontend_route_prefix') . '/pagesectionwidget');
        $this->crud->setEntityNameStrings('pagesectionwidget', 'pagesectionwidgets');

        $this->crud->addFields([
            [
                'name' => 'title',
                'label' => 'Title text'
            ],
            [
                'name' => 'subtitle',
                'label' => 'Subtitle'
            ],
            [
                'name' => 'image',
                'label' => 'Image',
                'type' => 'browse',
            ],
        ], 'update/create/both');
    }

    public function create()
    {
        //$this->crud->hasAccessOrFail('create');
        //dd($this->crud);

        // prepare the fields you need to show
        $this->data = $this->extraData;

        $this->data['crud'] = $this->crud;
        $this->data['saveAction'] = $this->getSaveAction();
        $this->data['fields'] = $this->crud->getCreateFields();
        $this->data['title'] = "Edit widget";

        // load the view from /resources/views/vendor/backpack/crud/ if it exists, otherwise load the one in the package
        return view($this->crud->getCreateView(), $this->data);

        //return parent::create(); // TODO: Change the autogenerated stub
    }

    public function setExtraData($data) {
        $this->extraData = $data;
    }
}
