<?php

namespace App\Http\Controllers\Widgets;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Backpack\CRUD\app\Http\Controllers\CrudController;
use Illuminate\Support\Facades\File;
use Illuminate\Support\Facades\Config;

class BannerWidget extends CrudController
{
    private $extraData;

    public function setup() {
        $this->crud->setModel('App\Models\PageSectionWidget');
        $this->crud->setRoute(config('backpack.base.frontend_route_prefix') . '/pagesectionwidget');
        $this->crud->setEntityNameStrings('pagesectionwidget', 'pagesectionwidgets');

        $this->crud->addFields([
            [
                'name' => 'title',
                'label' => 'Title text'
            ],
            [
                'name' => 'subtitle',
                'label' => 'Subtitle'
            ],
            [
                'name' => 'image',
                'label' => 'Image',
                'type' => 'browse',
            ],
        ], 'update/create/both');
    }

    public function create()
    {
        //$this->crud->hasAccessOrFail('create');
        //dd($this->crud);

        // prepare the fields you need to show
        $this->data = $this->extraData;

        $this->data['crud'] = $this->crud;
        $this->data['saveAction'] = $this->getSaveAction();
        $this->data['fields'] = $this->crud->getCreateFields();
        $this->data['title'] = "Edit widget";

        // load the view from /resources/views/vendor/backpack/crud/ if it exists, otherwise load the one in the package
        return view($this->crud->getCreateView(), $this->data);
    }

    public function edit($id)
    {
        return parent::edit($id); // TODO: Change the autogenerated stub
    }

    public function display($view)
    {
        return view('widget_types.' . $view, $this->data)->render();
    }

    public function setExtraData($data) {
        $this->extraData = $data;
    }

    public function setData($data) {
        $this->data['data'] = json_decode($data);
    }

    public function createSettings($requestData) {
        $background = str_replace("\\", "/", $requestData->input('widget_background'));
        return json_encode([
            'title' => $requestData->input('widget_title'),
            'subtitle' => $requestData->input('widget_subtitle'),
            'image' => $background
        ]);


    }
}
